export type AccessStatus = "accessible" | "partial" | "blocked" | "unknown"

export interface SiteInfo {
  id: string
  name: string
  domain: string
  category: string
  status: AccessStatus
  description: string
  lastUpdated: string
  notes?: string
  alternatives?: string[]
}

export const categories = [
  "全部",
  "搜索引擎",
  "社交媒体",
  "视频平台",
  "开发工具",
  "新闻媒体",
  "云服务",
  "通讯工具",
  "AI工具",
  "其他",
] as const

export type Category = (typeof categories)[number]

export const sites: SiteInfo[] = [
  // 搜索引擎
  {
    id: "google",
    name: "Google",
    domain: "google.com",
    category: "搜索引擎",
    status: "blocked",
    description: "全球最大的搜索引擎",
    lastUpdated: "2024-01",
    notes: "自2014年起被封锁",
    alternatives: ["百度", "必应", "搜狗"],
  },
  {
    id: "bing",
    name: "Bing",
    domain: "bing.com",
    category: "搜索引擎",
    status: "accessible",
    description: "微软搜索引擎",
    lastUpdated: "2024-01",
    notes: "cn.bing.com 正常访问",
  },
  {
    id: "duckduckgo",
    name: "DuckDuckGo",
    domain: "duckduckgo.com",
    category: "搜索引擎",
    status: "blocked",
    description: "注重隐私的搜索引擎",
    lastUpdated: "2024-01",
  },

  // 社交媒体
  {
    id: "facebook",
    name: "Facebook",
    domain: "facebook.com",
    category: "社交媒体",
    status: "blocked",
    description: "全球最大社交网络",
    lastUpdated: "2024-01",
    notes: "自2009年起被封锁",
    alternatives: ["微信", "微博", "QQ"],
  },
  {
    id: "twitter",
    name: "X (Twitter)",
    domain: "x.com",
    category: "社交媒体",
    status: "blocked",
    description: "微博客社交平台",
    lastUpdated: "2024-01",
    notes: "自2009年起被封锁",
    alternatives: ["微博"],
  },
  {
    id: "instagram",
    name: "Instagram",
    domain: "instagram.com",
    category: "社交媒体",
    status: "blocked",
    description: "图片分享社交平台",
    lastUpdated: "2024-01",
    notes: "自2014年起被封锁",
    alternatives: ["小红书", "微博"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    domain: "linkedin.com",
    category: "社交媒体",
    status: "blocked",
    description: "职业社交网络",
    lastUpdated: "2024-01",
    notes: "自2014年起被封锁",
    alternatives: ["脉脉", "BOSS直聘"],
  },
  {
    id: "reddit",
    name: "Reddit",
    domain: "reddit.com",
    category: "社交媒体",
    status: "blocked",
    description: "社区论坛平台",
    lastUpdated: "2024-01",
    alternatives: ["知乎", "贴吧"],
  },
  {
    id: "pinterest",
    name: "Pinterest",
    domain: "pinterest.com",
    category: "社交媒体",
    status: "blocked",
    description: "图片收集分享平台",
    lastUpdated: "2024-01",
    alternatives: ["花瓣网"],
  },
  {
    id: "tumblr",
    name: "Tumblr",
    domain: "tumblr.com",
    category: "社交媒体",
    status: "blocked",
    description: "轻博客平台",
    lastUpdated: "2024-01",
  },

  // 视频平台
  {
    id: "youtube",
    name: "YouTube",
    domain: "youtube.com",
    category: "视频平台",
    status: "blocked",
    description: "全球最大视频平台",
    lastUpdated: "2024-01",
    notes: "自2009年起被封锁",
    alternatives: ["哔哩哔哩", "优酷", "爱奇艺"],
  },
  {
    id: "tiktok",
    name: "TikTok",
    domain: "tiktok.com",
    category: "视频平台",
    status: "blocked",
    description: "短视频平台国际版",
    lastUpdated: "2024-01",
    notes: "抖音国际版",
    alternatives: ["抖音"],
  },
  {
    id: "vimeo",
    name: "Vimeo",
    domain: "vimeo.com",
    category: "视频平台",
    status: "blocked",
    description: "高品质视频分享平台",
    lastUpdated: "2024-01",
  },
  {
    id: "twitch",
    name: "Twitch",
    domain: "twitch.tv",
    category: "视频平台",
    status: "blocked",
    description: "游戏直播平台",
    lastUpdated: "2024-01",
    alternatives: ["斗鱼", "虎牙", "哔哩哔哩直播"],
  },
  {
    id: "netflix",
    name: "Netflix",
    domain: "netflix.com",
    category: "视频平台",
    status: "blocked",
    description: "流媒体视频平台",
    lastUpdated: "2024-01",
    alternatives: ["爱奇艺", "优酷", "腾讯视频"],
  },

  // 开发工具
  {
    id: "github",
    name: "GitHub",
    domain: "github.com",
    category: "开发工具",
    status: "partial",
    description: "代码托管平台",
    lastUpdated: "2024-01",
    notes: "访问速度较慢，部分资源需加速",
    alternatives: ["Gitee", "GitLab"],
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    domain: "stackoverflow.com",
    category: "开发工具",
    status: "accessible",
    description: "开发者问答社区",
    lastUpdated: "2024-01",
  },
  {
    id: "gitlab",
    name: "GitLab",
    domain: "gitlab.com",
    category: "开发工具",
    status: "partial",
    description: "代码托管平台",
    lastUpdated: "2024-01",
    notes: "访问可能不稳定",
  },
  {
    id: "npm",
    name: "npm",
    domain: "npmjs.com",
    category: "开发工具",
    status: "partial",
    description: "JavaScript 包管理器",
    lastUpdated: "2024-01",
    notes: "建议使用国内镜像",
    alternatives: ["npmmirror.com"],
  },
  {
    id: "docker",
    name: "Docker Hub",
    domain: "hub.docker.com",
    category: "开发工具",
    status: "partial",
    description: "容器镜像仓库",
    lastUpdated: "2024-01",
    notes: "访问速度较慢",
  },
  {
    id: "vercel",
    name: "Vercel",
    domain: "vercel.com",
    category: "开发工具",
    status: "partial",
    description: "前端部署平台",
    lastUpdated: "2024-01",
    notes: "主站可访问，部分部署域名被封",
  },
  {
    id: "netlify",
    name: "Netlify",
    domain: "netlify.com",
    category: "开发工具",
    status: "partial",
    description: "静态网站托管平台",
    lastUpdated: "2024-01",
    notes: "主站可访问，部分功能受限",
  },
  {
    id: "codepen",
    name: "CodePen",
    domain: "codepen.io",
    category: "开发工具",
    status: "accessible",
    description: "前端代码演示平台",
    lastUpdated: "2024-01",
  },
  {
    id: "codesandbox",
    name: "CodeSandbox",
    domain: "codesandbox.io",
    category: "开发工具",
    status: "accessible",
    description: "在线代码编辑器",
    lastUpdated: "2024-01",
  },

  // 新闻媒体
  {
    id: "nytimes",
    name: "纽约时报",
    domain: "nytimes.com",
    category: "新闻媒体",
    status: "blocked",
    description: "美国主流媒体",
    lastUpdated: "2024-01",
  },
  {
    id: "wsj",
    name: "华尔街日报",
    domain: "wsj.com",
    category: "新闻媒体",
    status: "blocked",
    description: "财经新闻媒体",
    lastUpdated: "2024-01",
  },
  {
    id: "bbc",
    name: "BBC",
    domain: "bbc.com",
    category: "新闻媒体",
    status: "blocked",
    description: "英国广播公司",
    lastUpdated: "2024-01",
  },
  {
    id: "reuters",
    name: "Reuters",
    domain: "reuters.com",
    category: "新闻媒体",
    status: "blocked",
    description: "路透社",
    lastUpdated: "2024-01",
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    domain: "bloomberg.com",
    category: "新闻媒体",
    status: "partial",
    description: "彭博社",
    lastUpdated: "2024-01",
    notes: "部分内容可访问",
  },
  {
    id: "medium",
    name: "Medium",
    domain: "medium.com",
    category: "新闻媒体",
    status: "blocked",
    description: "博客平台",
    lastUpdated: "2024-01",
  },

  // 云服务
  {
    id: "aws",
    name: "AWS",
    domain: "aws.amazon.com",
    category: "云服务",
    status: "accessible",
    description: "亚马逊云服务",
    lastUpdated: "2024-01",
    notes: "AWS 中国区需单独注册",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    domain: "cloud.google.com",
    category: "云服务",
    status: "blocked",
    description: "谷歌云平台",
    lastUpdated: "2024-01",
    alternatives: ["阿里云", "腾讯云", "华为云"],
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    domain: "azure.microsoft.com",
    category: "云服务",
    status: "accessible",
    description: "微软云平台",
    lastUpdated: "2024-01",
    notes: "Azure 中国区需单独注册",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    domain: "dropbox.com",
    category: "云服务",
    status: "blocked",
    description: "云存储服务",
    lastUpdated: "2024-01",
    alternatives: ["百度网盘", "阿里云盘"],
  },
  {
    id: "gdrive",
    name: "Google Drive",
    domain: "drive.google.com",
    category: "云服务",
    status: "blocked",
    description: "谷歌云盘",
    lastUpdated: "2024-01",
    alternatives: ["百度网盘", "阿里云盘"],
  },

  // 通讯工具
  {
    id: "whatsapp",
    name: "WhatsApp",
    domain: "whatsapp.com",
    category: "通讯工具",
    status: "blocked",
    description: "即时通讯应用",
    lastUpdated: "2024-01",
    alternatives: ["微信"],
  },
  {
    id: "telegram",
    name: "Telegram",
    domain: "telegram.org",
    category: "通讯工具",
    status: "blocked",
    description: "加密通讯应用",
    lastUpdated: "2024-01",
    alternatives: ["微信"],
  },
  {
    id: "discord",
    name: "Discord",
    domain: "discord.com",
    category: "通讯工具",
    status: "blocked",
    description: "游戏语音通讯平台",
    lastUpdated: "2024-01",
    alternatives: ["QQ", "YY语音"],
  },
  {
    id: "slack",
    name: "Slack",
    domain: "slack.com",
    category: "通讯工具",
    status: "partial",
    description: "企业协作工具",
    lastUpdated: "2024-01",
    notes: "访问可能不稳定",
    alternatives: ["钉钉", "飞书", "企业微信"],
  },
  {
    id: "zoom",
    name: "Zoom",
    domain: "zoom.us",
    category: "通讯工具",
    status: "partial",
    description: "视频会议平台",
    lastUpdated: "2024-01",
    notes: "有中国区服务",
    alternatives: ["腾讯会议", "钉钉"],
  },
  {
    id: "skype",
    name: "Skype",
    domain: "skype.com",
    category: "通讯工具",
    status: "partial",
    description: "视频通话应用",
    lastUpdated: "2024-01",
    notes: "部分功能可用",
  },

  // AI工具
  {
    id: "chatgpt",
    name: "ChatGPT",
    domain: "chat.openai.com",
    category: "AI工具",
    status: "blocked",
    description: "OpenAI 聊天机器人",
    lastUpdated: "2024-01",
    alternatives: ["文心一言", "通义千问", "讯飞星火"],
  },
  {
    id: "openai",
    name: "OpenAI",
    domain: "openai.com",
    category: "AI工具",
    status: "blocked",
    description: "AI 研究公司",
    lastUpdated: "2024-01",
    notes: "API 也无法直接访问",
  },
  {
    id: "claude",
    name: "Claude",
    domain: "claude.ai",
    category: "AI工具",
    status: "blocked",
    description: "Anthropic AI 助手",
    lastUpdated: "2024-01",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    domain: "midjourney.com",
    category: "AI工具",
    status: "blocked",
    description: "AI 图像生成",
    lastUpdated: "2024-01",
    notes: "需通过 Discord 使用",
  },
  {
    id: "gemini",
    name: "Gemini",
    domain: "gemini.google.com",
    category: "AI工具",
    status: "blocked",
    description: "Google AI 助手",
    lastUpdated: "2024-01",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    domain: "huggingface.co",
    category: "AI工具",
    status: "partial",
    description: "AI 模型社区",
    lastUpdated: "2024-01",
    notes: "主站可访问，部分模型下载慢",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    domain: "perplexity.ai",
    category: "AI工具",
    status: "blocked",
    description: "AI 搜索引擎",
    lastUpdated: "2024-01",
  },

  // 其他
  {
    id: "wikipedia",
    name: "Wikipedia",
    domain: "wikipedia.org",
    category: "其他",
    status: "blocked",
    description: "维基百科",
    lastUpdated: "2024-01",
    notes: "中文维基百科被封锁",
    alternatives: ["百度百科", "知乎"],
  },
  {
    id: "spotify",
    name: "Spotify",
    domain: "spotify.com",
    category: "其他",
    status: "blocked",
    description: "音乐流媒体平台",
    lastUpdated: "2024-01",
    alternatives: ["网易云音乐", "QQ音乐"],
  },
  {
    id: "apple",
    name: "Apple",
    domain: "apple.com",
    category: "其他",
    status: "accessible",
    description: "苹果官网",
    lastUpdated: "2024-01",
  },
  {
    id: "paypal",
    name: "PayPal",
    domain: "paypal.com",
    category: "其他",
    status: "accessible",
    description: "在线支付平台",
    lastUpdated: "2024-01",
    notes: "可访问但中国区功能受限",
  },
  {
    id: "figma",
    name: "Figma",
    domain: "figma.com",
    category: "其他",
    status: "accessible",
    description: "设计协作平台",
    lastUpdated: "2024-01",
  },
  {
    id: "notion",
    name: "Notion",
    domain: "notion.so",
    category: "其他",
    status: "partial",
    description: "协作文档工具",
    lastUpdated: "2024-01",
    notes: "访问速度可能较慢",
  },
  {
    id: "canva",
    name: "Canva",
    domain: "canva.com",
    category: "其他",
    status: "accessible",
    description: "在线设计工具",
    lastUpdated: "2024-01",
  },
]

export function getSitesByCategory(category: Category): SiteInfo[] {
  if (category === "全部") {
    return sites
  }
  return sites.filter((site) => site.category === category)
}

export function searchSites(query: string): SiteInfo[] {
  const lowerQuery = query.toLowerCase()
  return sites.filter(
    (site) =>
      site.name.toLowerCase().includes(lowerQuery) ||
      site.domain.toLowerCase().includes(lowerQuery) ||
      site.description.toLowerCase().includes(lowerQuery)
  )
}

export function getStatusStats() {
  const stats = {
    accessible: 0,
    partial: 0,
    blocked: 0,
    unknown: 0,
    total: sites.length,
  }

  sites.forEach((site) => {
    stats[site.status]++
  })

  return stats
}
